language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ds-codeigniter' ]; then cd .. && eval "mv $currentfolder generator-ds-codeigniter" && cd generator-ds-codeigniter; fi

